name: Release and Publish

on:
  release:
    types: [published]

env:
  NODE_VERSION: 20.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build:production
          npm pack
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: "la-ots-pelican-wlf-theme-*.tgz"

  publish-npm:
    name: Release to NPM
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: NPM
      url: https://www.npmjs.com/package/@la-ots/pelican-wlf-theme

    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: release
      
      - name: Setup Node ${{ env.NODE_VERSION }} for NPM
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Publish to NPM
        if: '!github.event.release.prerelease'
        run: npm publish $(ls *.tgz) --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.LAOTS_NPM_TOKEN }}
      
      - name: Publish to NPM
        if: 'github.event.release.prerelease'
        run: npm publish $(ls *.tgz) --provenance --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.LAOTS_NPM_TOKEN }}
